import React from 'react';
import Image from 'next/image';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';

export default function TermsConditions() {
  return (
    <>
        <NavBar/>
        <div className="min-h-screen bg-white text-black">
            <div className="container mx-auto px-4 py-12 md:py-20">
                <div className="grid md:grid-cols-2 gap-8 items-center">
                <div>
                    <h1 className="text-3xl md:text-4xl font-bold text-teal-700 mb-6">
                    Terms & Conditions
                    </h1>
                    <div className="prose max-w-prose">
                    <p className="text-sm md:text-base leading-relaxed">
                    By using the services of Palecha Tours and Travels you agree to the following Terms and Conditions. Please read them carefully.
                    </p>
                    </div>
                </div>
                
                <div className="hidden md:block">
                    <div className="relative w-full max-w-[700px] aspect-video">
                    <Image 
                        src="/images/palecha_logo.jpg" 
                        alt="Travel Terms Illustration" 
                        fill
                        className="object-cover rounded-lg shadow-lg ml-7"
                        placeholder="blur"
                        blurDataURL="/images/palecha_logo.jpg"
                    />
                    </div>
                </div>
                </div>

                <div className="mt-12 bg-teal-50 p-6 rounded-lg prose max-w-none">
                    <h2 className="text-2xl font-bold text-teal-700 mb-4">1. AI-Powered Itinerary Creation</h2>
                    <p>1.1 Our AI tool (&quot;Travel Buddy&quot;) is designed to assist in creating travel itineraries based on the information provided by users.</p>
                    <p>1.2 While we strive for accuracy, itineraries generated by Travel Buddy may contain errors or omissions. Users are responsible for reviewing the itinerary before finalizing it.</p>

                    <h2 className="text-2xl font-bold text-teal-700 mb-4 mt-6">2. Role of Travel Experts</h2>
                    <p>2.1 Once you finalize your AI-generated itinerary, our travel experts will review it for accuracy, feasibility, and cost-effectiveness.</p>
                    <p>2.2 Our team will contact you to confirm your itinerary, suggest changes (if necessary), and assist with bookings.</p>
                    <p>2.3 Travel Buddy will not initiate or complete bookings without your explicit approval.</p>

                    <h2 className="text-2xl font-bold text-teal-700 mb-4 mt-6">3. Booking and Payments</h2>
                    <p>3.1 All bookings will be handled by our team after your approval. Travel Buddy itself does not process payments or reservations.</p>
                    <p>3.2 You are responsible for providing accurate personal and payment details to complete bookings.</p>
                    <p>3.3 Any payment disputes or cancellations will follow the policies of the respective service providers (hotels, airlines, etc.).</p>

                    <h2 className="text-2xl font-bold text-teal-700 mb-4 mt-6">4. Limitations of Liability</h2>
                    <p>4.1 We are not liable for errors or omissions in AI-generated itineraries.</p>
                    <p>4.2 We are not responsible for any issues arising from third-party services (e.g., hotel cancellations, flight delays).</p>
                    <p>4.3 In the event of unforeseen circumstances (e.g., natural disasters, strikes), we will do our best to assist but cannot guarantee resolutions or refunds.</p>

                    <h2 className="text-2xl font-bold text-teal-700 mb-4 mt-6">5. User Responsibilities</h2>
                    <p>5.1 You are responsible for providing accurate information (e.g., travel dates, preferences) to generate your itinerary.</p>
                    <p>5.2 It is your responsibility to ensure that all travel documents (passports, visas, etc.) are valid and up to date.</p>

                    <h2 className="text-2xl font-bold text-teal-700 mb-4 mt-6">6. Data Privacy</h2>
                    <p>6.1 Any personal information provided will be handled in accordance with our Privacy Policy.</p>
                    <p>6.2 We use your data solely for itinerary creation, bookings, and to enhance your travel planning experience.</p>

                    <h2 className="text-2xl font-bold text-teal-700 mb-4 mt-6">7. Cancellation and Refunds</h2>
                    <p>7.1 Cancellations and refunds are subject to the policies of the service providers (hotels, airlines, etc.).</p>
                    <p>7.2 Our travel experts will assist with cancellations or changes but cannot guarantee refunds from third parties.</p>

                    <h2 className="text-2xl font-bold text-teal-700 mb-4 mt-6">8. Changes to Terms</h2>
                    <p>8.1 We reserve the right to update these Terms and Conditions at any time. Changes will be effective immediately upon posting on our website.</p>

                    <h2 className="text-2xl font-bold text-teal-700 mb-4 mt-6">9. Contact Us</h2>
                    <p>If you have any questions or concerns, please contact us at:</p>
                    <p> Palechatoursandtravels1@gmail.com | +91 85598 02030</p>

                    <p className="mt-6 italic">By using our services, you agree to these Terms and Conditions. Thank you for choosing Palecha Tours and Travels.</p>
                </div>

                <div className="text-center mt-12">
                <p className="text-sm text-gray-600">
                    Last Updated: November 2024 | Palecha Tours and Travel
                </p>
                </div>
            </div>
        </div>
        <Footer/>
    </>
  );
}